informatics-isi-edu/deriva-webapps

treeview/Makefile, treeview/gridexample.html, treeview/js/main.js
=> Added MakeFile for review.

treeview/index.html, treeview/js/main.js
1. Horizontal scrollbar issue fixed.
2. Theiler Stage drop down data changed to Join using name instead of 
ID.
3. refresh_tree=true Handling commented for later use.
=> Horizontal scrollbar issue fixed, Theiler Stage data source fixed

treeview/index.html, treeview/js/main.js, treeview/themes/default/images/style.css
Search bar and drop down flickering issue resolved.
=> Flickering issue solved.

treeview/js/main.js
Not detected icon is now visible.
=> Fixed the label problem for tree.

boolean-search/booleansearch.app.js, boolean-search/index.html, boolean-search/styles/booleansearch.css, treeview/README.md, treeview/index.html, treeview/js/main.js, treeview/treeview-config.js
- Integrated treeview with boolean search
- Added a config file in treeview. The config file has an object for callback functions on node click
- Added a Readme in treeview for explaining how to use the node click callbacks
=> Integrate tree view

boolean-search/index.html, boolean-search/styles/booleansearch.css, treeview/index.html, treeview/js/main.js, treeview/themes/default/images/style.css
- Made the treeview division in boolean-search of fixed width with min and max
- made treeview responsive based on width of window
=> Style changes in treeview and boolean-search

boolean-search/booleansearch.app.js, heatmap/heatmap.js
- Added proper referrer, source and column  attributes in the header
- Added ppid and pcid as query params in requests to recordset
- Made schema request's action to be "model/read"
=> logging in heatmap and boolean-search

boolean-search/booleansearch.app.js, boolean-search/styles/booleansearch.css
- There were 3 things in the JavaScript code that were not compatible with Internet Explorer:
1. JavaScript classes : Replaced with functions
2. Delta functions: Replaced with functions that have return statements
3. Array.includes(): replaced it with Array.indexOf(string) >=0
=> Made changes to make app compatible with IE

treeview/index.html, treeview/js/main.js, treeview/themes/default/images/style.css
Reverts informatics-isi-edu/deriva-webapps#54
=> Revert "added navbar to the treeview"

Makefile, test/e2e/README.md, test/e2e/config.js, test/e2e/specs/main.spec.js, test/e2e/specs/protractor.conf.js, test/e2e/utils/common/httpFun.js
- created Makefile
- created data_setup folder
- created specs folder
- created utils folder
- created config.js
- created README.md
=> test cases skeleton for deriva-webapps

test/e2e/config.js, test/e2e/specs/treeview/00-dynamic-treeview.spec.js, test/e2e/specs/treeview/00-static-treeview.spec.js, test/e2e/specs/treeview/dynamic-treeview-expected-value.js, test/e2e/specs/treeview/static-treeview-expected-value.js, test/e2e/utils/common/deriva-webapps.js
Static treeview
- hierarcy testcase for opening and closing of node list
- action buttons: search and expand alland collapse all button test
- filter terms based on sepcific Theiler Stage
Dynamic treeview
- hierarchy testcase for opening and closing of node list
- search feature test
- error messages correctly displayed
=> test($core): functional testcases for treeview

.gitignore, boolean-search/booleansearch.app.js, boolean-search/index.html, boolean-search/styles/booleansearch.css
After applying the new design to chaise, we found out that the height in boolean search is not properly defined. After investigating this, I realized that even with the old design, the height was not proper. We were setting the height blindly to "96%" and assumed that is going to always work.
In this PR, I had to modify the structure and css so I could run the same function that chaise is using for setting the height. 
As part of this, I also changed the chaise URLs to be aligned with other deriva-webapps (by using relative paths instead of absolute).
You can take a look at it here: https://dev.rebuildingakidney.org/~ashafaei/web-apps/boolean-search/
P.S. If you try this with current chaise it will fail because `UiUtils` in `utils.js` is using some constants that are defined in …
=> fix height issue in boolean search

plot/index.html, plot/plot-config-sample.js, plot/plot.app.js, plot/styles/plot.css
Changes to support violin plots in the pot app. Make sure to create `plot-config.js` in the directory on the server to use the violin plot feature detailed in `plot-config-somaple.js`.
=> Violin plot support

.gitignore, plot/index.html, plot/plot.app.js, plot/styles/plot.css
This PR contains the changes for multi study support. With this support also comes the ability to embed in study and gene pages which provides a few unique scenarios outlined [here](https://github.com/informatics-isi-edu/deriva-webapps/issues/100#issuecomment-722776170).
Other included changes are:
- Study information is based on selected gene
- each time study selector is opened, a new set of genes are fetched to align with the selected studies
- Allow for "All Studies" to be selected which fetches data for the graph without defining a study parameter.
-  NOTE: this only works if queryPattern is properly defined
- Allow for removing all studies and clearing the graph of data
- gene information can be changed now and is based on the defined study/studies if any.
- gene is required to …
=> Version 1.2 support

plot/README.md, plot/index.html, plot/plot.app.js, plot/styles/plot.css
This PR adds responsiveness to the plot app as described in this comment in the connected issue. Opening the PR so we can link/track the changes made to accommodate the concerns listed in the attached issue.
=> Responsive plot

boolean-search/booleansearch.app.js, lineplot/lineplot.app.js, plot/plot.app.js
The changes in this PR correspond with changes in [Chaise PR 2059](https://github.com/informatics-isi-edu/chaise/pull/2059). This should be merged after the chaise PR is merged.
=> Update config app parameters

src/components/search-bar.tsx, src/components/virtualized-select.tsx
- removed excessive memoization
this fixes #133
=> React matrix search width bug

src/components/heatmap/heatmap.tsx
2 cases to handle for 404 Not Found:
1) There is no heatmap data available for the given “id” (but the record with that id exists)
2) There is no record with the given “id” (and therefore there is no heatmap data that exists)
Issue link : https://github.com/informatics-isi-edu/deriva-webapps/issues/74
=> Added error message for invalid id and no data scenario

config/plot-config-sample.js, docs/user-docs/plot-app.md, src/hooks/chart.ts
Check for queryPattern support for all plot types
=> Support queryPattern for all plot types

docs/user-docs/plot-functionality.md, src/components/plot/chart-with-effect.tsx, src/hooks/chart-select-grid.ts, src/hooks/chart.ts, src/models/plot.ts, src/utils/config.ts, src/utils/string.ts, src/utils/window-ref.ts
Improvements to enhance the visibility of the plot in certain configurations where the x-axis labels can be excessively long, resulting in a small display of the plot. The enhancements include:
- Increased Viewport Size: The size of the viewport has been increased to expand the plot area for all plots.
- Legends Wrapping: Implemented a step function to wrap the legend text based on the screen size, ensuring that the width of the legends is limited to a certain value relative to the plot area. This prevents the legends from occupying excessive space and affecting the visibility of the plot along with resizing window handling.
- Additional Functions: Two new functions, wrapText and extractValue, have been introduced. These functions are utilized to either wrap the legend text or extract a …
=> Plot app: Wrap and Truncate labels for x axis and legend shown for violin plot

docs/dev-docs/plot-config-test.js, docs/user-docs/plot-app.md, src/components/plot/chart-with-effect.tsx, src/hooks/chart-select-grid.ts, src/hooks/chart.ts, src/models/plot.ts, src/utils/message-map.ts, src/utils/string.ts
Add support for parsing any query parameters. Allow for type, mode, and marker to be set for each "trace" in the plot. Improve support for line plot use case.
Other changes include parsing all plot data in a general function and only updating the data for each plot type as needed. Improved support for x_col and y_col arrays when parsing 2d and 3d data. Fixed numerous bugs found while testing with the plot-configtest.js.
=> Plotly data properties

src/hooks/chart.ts, src/hooks/control.ts
Pseudo code for handling all 3 cases for fetching data. Also fixes a bug in multi trace views after updating the filtering data
=> Pseudo code for reference, http, data

src/assets/scss/_matrix.scss, src/components/matrix/grid-button.tsx, src/components/matrix/grid-cell.tsx, src/components/matrix/row-headers.tsx, src/components/matrix/virtualized-grid.tsx
After looking at the existing deployed mousematrix facebase, we noticed new border changes and decided to make similar changes to the React version.
While making these changes, I also refactored the `grid-button.tsx` to use font-awesome instead of SVGs.
=> Matrix border changes

config/matrix-config-sample.js, docs/user-docs/matrix-app.md, src/assets/scss/_matrix.scss, src/components/matrix/column-tree-headers.tsx, src/components/matrix/grid-cell.tsx, src/components/matrix/row-headers.tsx, src/components/matrix/row-tree-headers.tsx, src/components/matrix/virtualized-grid.tsx, src/hooks/matrix.ts, src/models/matrix-config.ts, src/pages/matrix.tsx, src/utils/ui-utils.ts
The new features and changes are,
- Allow row header, column header, legend, and cell links to be defined using `handlebars` patterns.
- Add the ability to define the value that should be displayed for cells.
- Allow customization of color palette options.
- Allow hiding the legend.
- Style changes: 
- Remove extra space above the page
- Add border to the bottom of the grid
- Ensure links use the same style as chaise.
- The code was assuming that we're always showing horizontal and vertical scrollbars in the grid, but now I'm checking that with JavaScript.
P.S. I wanted to apply the matrix config changes with these changes, but since this feature is a priority, we decided to merge the PR as is. That said, config changes would probably require changing how I implemented some features here.
=> Add features to matrix app for altas usecase

src/components/plot/plot-control-grid.tsx, src/components/plot/user-controls-grid.tsx, src/hooks/chart.ts, src/models/plot.ts, src/pages/plot.tsx, src/providers/plot-app.tsx, src/utils/plot-utils.ts
Resolves: #201 
Validation issues handled:
1. grid_layout_config -> cols: Ignored/Handled and app will work fine.
2. user_control -> uid : Blocking error will be displayed for local and global controls
3. user_control -> type: Control won't be shown and an alert will be shown with error.
4. user_control -> label: No label will be shown and no error will be shown
5. user_control .request_info.data/url_pattern: Control won't be shown & an alert will be shown with type warning
6. layout -> source_uid: An alert will be shown with type error and the control will be shown without any layout parameters applied to it.
7. layout -> w/h/x/y: Control/plot won't be shown and an alert will be shown with the type warning
8. Plots/Control with same uid: An alert will be shown with type error and the …
=> Plot grid layout validation
